# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from protos import celaut_pb2 as celaut__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='compile.proto',
  package='compile',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcompile.proto\x12\x07\x63ompile\x1a\x0c\x63\x65laut.proto\"\x85\x06\n\x07Service\x12-\n\tcontainer\x18\x01 \x01(\x0b\x32\x1a.compile.Service.Container\x12 \n\x03\x61pi\x18\x02 \x01(\x0b\x32\x13.celaut.Service.Api\x12&\n\x06tensor\x18\x03 \x01(\x0b\x32\x16.celaut.Service.Tensor\x12&\n\x06ledger\x18\x04 \x01(\x0b\x32\x16.celaut.Service.Ledger\x1a\xd8\x04\n\tContainer\x12\x14\n\x0c\x61rchitecture\x18\x01 \x01(\x0c\x12\x38\n\nfilesystem\x18\x02 \x01(\x0b\x32$.celaut.Service.Container.Filesystem\x12Q\n\x14\x65nviroment_variables\x18\x03 \x03(\x0b\x32\x33.compile.Service.Container.EnviromentVariablesEntry\x12\x12\n\nentrypoint\x18\x04 \x03(\t\x12\x30\n\x06\x63onfig\x18\x05 \x01(\x0b\x32 .celaut.Service.Container.Config\x12\x43\n\x10\x65xpected_gateway\x18\x06 \x01(\x0b\x32).celaut.Service.Container.ExpectedGateway\x1a\xce\x01\n\nFilesystem\x12@\n\x06\x62ranch\x18\x01 \x03(\x0b\x32\x30.compile.Service.Container.Filesystem.ItemBranch\x1a~\n\nItemBranch\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x04\x66ile\x18\x02 \x01(\x0cH\x00\x12\x0e\n\x04link\x18\x03 \x01(\tH\x00\x12:\n\nfilesystem\x18\x04 \x01(\x0b\x32$.celaut.Service.Container.FilesystemH\x00\x42\x06\n\x04item\x1aL\n\x18\x45nviromentVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.celaut.FieldDef:\x02\x38\x01\"\\\n\x0fServiceWithMeta\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.celaut.Any.Metadata\x12!\n\x07service\x18\x02 \x01(\x0b\x32\x10.compile.Serviceb\x06proto3'
  ,
  dependencies=[celaut__pb2.DESCRIPTOR,])




_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH = _descriptor.Descriptor(
  name='ItemBranch',
  full_name='compile.Service.Container.Filesystem.ItemBranch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='compile.Service.Container.Filesystem.ItemBranch.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='compile.Service.Container.Filesystem.ItemBranch.file', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link', full_name='compile.Service.Container.Filesystem.ItemBranch.link', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filesystem', full_name='compile.Service.Container.Filesystem.ItemBranch.filesystem', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='item', full_name='compile.Service.Container.Filesystem.ItemBranch.item',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=610,
  serialized_end=736,
)

_SERVICE_CONTAINER_FILESYSTEM = _descriptor.Descriptor(
  name='Filesystem',
  full_name='compile.Service.Container.Filesystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='branch', full_name='compile.Service.Container.Filesystem.branch', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=736,
)

_SERVICE_CONTAINER_ENVIROMENTVARIABLESENTRY = _descriptor.Descriptor(
  name='EnviromentVariablesEntry',
  full_name='compile.Service.Container.EnviromentVariablesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='compile.Service.Container.EnviromentVariablesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='compile.Service.Container.EnviromentVariablesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=814,
)

_SERVICE_CONTAINER = _descriptor.Descriptor(
  name='Container',
  full_name='compile.Service.Container',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='architecture', full_name='compile.Service.Container.architecture', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filesystem', full_name='compile.Service.Container.filesystem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enviroment_variables', full_name='compile.Service.Container.enviroment_variables', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entrypoint', full_name='compile.Service.Container.entrypoint', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='compile.Service.Container.config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expected_gateway', full_name='compile.Service.Container.expected_gateway', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SERVICE_CONTAINER_FILESYSTEM, _SERVICE_CONTAINER_ENVIROMENTVARIABLESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=814,
)

_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='compile.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='compile.Service.container', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api', full_name='compile.Service.api', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tensor', full_name='compile.Service.tensor', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ledger', full_name='compile.Service.ledger', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SERVICE_CONTAINER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=814,
)


_SERVICEWITHMETA = _descriptor.Descriptor(
  name='ServiceWithMeta',
  full_name='compile.ServiceWithMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='compile.ServiceWithMeta.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service', full_name='compile.ServiceWithMeta.service', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=816,
  serialized_end=908,
)

_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.fields_by_name['filesystem'].message_type = celaut__pb2._SERVICE_CONTAINER_FILESYSTEM
_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.containing_type = _SERVICE_CONTAINER_FILESYSTEM
_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.oneofs_by_name['item'].fields.append(
  _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.fields_by_name['file'])
_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.fields_by_name['file'].containing_oneof = _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.oneofs_by_name['item']
_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.oneofs_by_name['item'].fields.append(
  _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.fields_by_name['link'])
_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.fields_by_name['link'].containing_oneof = _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.oneofs_by_name['item']
_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.oneofs_by_name['item'].fields.append(
  _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.fields_by_name['filesystem'])
_SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.fields_by_name['filesystem'].containing_oneof = _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH.oneofs_by_name['item']
_SERVICE_CONTAINER_FILESYSTEM.fields_by_name['branch'].message_type = _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH
_SERVICE_CONTAINER_FILESYSTEM.containing_type = _SERVICE_CONTAINER
_SERVICE_CONTAINER_ENVIROMENTVARIABLESENTRY.fields_by_name['value'].message_type = celaut__pb2._FIELDDEF
_SERVICE_CONTAINER_ENVIROMENTVARIABLESENTRY.containing_type = _SERVICE_CONTAINER
_SERVICE_CONTAINER.fields_by_name['filesystem'].message_type = celaut__pb2._SERVICE_CONTAINER_FILESYSTEM
_SERVICE_CONTAINER.fields_by_name['enviroment_variables'].message_type = _SERVICE_CONTAINER_ENVIROMENTVARIABLESENTRY
_SERVICE_CONTAINER.fields_by_name['config'].message_type = celaut__pb2._SERVICE_CONTAINER_CONFIG
_SERVICE_CONTAINER.fields_by_name['expected_gateway'].message_type = celaut__pb2._SERVICE_CONTAINER_EXPECTEDGATEWAY
_SERVICE_CONTAINER.containing_type = _SERVICE
_SERVICE.fields_by_name['container'].message_type = _SERVICE_CONTAINER
_SERVICE.fields_by_name['api'].message_type = celaut__pb2._SERVICE_API
_SERVICE.fields_by_name['tensor'].message_type = celaut__pb2._SERVICE_TENSOR
_SERVICE.fields_by_name['ledger'].message_type = celaut__pb2._SERVICE_LEDGER
_SERVICEWITHMETA.fields_by_name['metadata'].message_type = celaut__pb2._ANY_METADATA
_SERVICEWITHMETA.fields_by_name['service'].message_type = _SERVICE
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['ServiceWithMeta'] = _SERVICEWITHMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), {

  'Container' : _reflection.GeneratedProtocolMessageType('Container', (_message.Message,), {

    'Filesystem' : _reflection.GeneratedProtocolMessageType('Filesystem', (_message.Message,), {

      'ItemBranch' : _reflection.GeneratedProtocolMessageType('ItemBranch', (_message.Message,), {
        'DESCRIPTOR' : _SERVICE_CONTAINER_FILESYSTEM_ITEMBRANCH,
        '__module__' : 'compile_pb2'
        # @@protoc_insertion_point(class_scope:compile.Service.Container.Filesystem.ItemBranch)
        })
      ,
      'DESCRIPTOR' : _SERVICE_CONTAINER_FILESYSTEM,
      '__module__' : 'compile_pb2'
      # @@protoc_insertion_point(class_scope:compile.Service.Container.Filesystem)
      })
    ,

    'EnviromentVariablesEntry' : _reflection.GeneratedProtocolMessageType('EnviromentVariablesEntry', (_message.Message,), {
      'DESCRIPTOR' : _SERVICE_CONTAINER_ENVIROMENTVARIABLESENTRY,
      '__module__' : 'compile_pb2'
      # @@protoc_insertion_point(class_scope:compile.Service.Container.EnviromentVariablesEntry)
      })
    ,
    'DESCRIPTOR' : _SERVICE_CONTAINER,
    '__module__' : 'compile_pb2'
    # @@protoc_insertion_point(class_scope:compile.Service.Container)
    })
  ,
  'DESCRIPTOR' : _SERVICE,
  '__module__' : 'compile_pb2'
  # @@protoc_insertion_point(class_scope:compile.Service)
  })
_sym_db.RegisterMessage(Service)
_sym_db.RegisterMessage(Service.Container)
_sym_db.RegisterMessage(Service.Container.Filesystem)
_sym_db.RegisterMessage(Service.Container.Filesystem.ItemBranch)
_sym_db.RegisterMessage(Service.Container.EnviromentVariablesEntry)

ServiceWithMeta = _reflection.GeneratedProtocolMessageType('ServiceWithMeta', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEWITHMETA,
  '__module__' : 'compile_pb2'
  # @@protoc_insertion_point(class_scope:compile.ServiceWithMeta)
  })
_sym_db.RegisterMessage(ServiceWithMeta)


_SERVICE_CONTAINER_ENVIROMENTVARIABLESENTRY._options = None
# @@protoc_insertion_point(module_scope)
