python3 -m grpc_tools.protoc -I. --python_out=. buffer.proto --experimental_allow_proto3_optional
python3 -m grpc_tools.protoc -I. --python_out=. celaut.proto --experimental_allow_proto3_optional
python3 -m grpc_tools.protoc -I. --python_out=. test.proto --experimental_allow_proto3_optional
python3 -m grpc_tools.protoc -I. --python_out=. compile.proto --experimental_allow_proto3_optional